# Thermal Data Collection

Derive the Mars coordinates of every image in `data/final_data/image_dataset.json`
and turn them into a THEMIS retrieval plan, saved under `data/thermal_data/`.

The pipeline this feeds:

1. **This notebook** — image -> centre latitude/longitude -> deduplicated query sites.
2. **`themis_measurements.py`** (Phase 1) — site -> THEMIS observation IDs covering it,
   with acquisition time and Mars local solar time.
3. **`themis_id_to_thermal_value.py`** (Phase 2) — observation ID -> decoded
   brightness-temperature matrix (`.npy`).

The model consumes a small window at **native THEMIS resolution (~100 m/pixel)**,
not a raster upsampled to the HiRISE grid, so what we need per site is a
`32 x 32` THEMIS patch per timestep rather than a full-resolution image.

In [1]:
%load_ext autoreload
%autoreload 2

import os
import json
import subprocess
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

from themis_coordinates import center_latlon, ground_extent_m, THEMIS_GSD_M

DATA_PATH = "data"
DATASET_JSON = os.path.join(DATA_PATH, "final_data", "image_dataset.json")

THERMAL_DIR = os.path.join(DATA_PATH, "thermal_data")
THEMIS_DIR = os.path.join(THERMAL_DIR, "themis_data")      # real THEMIS products
GENERATED_DIR = os.path.join(THERMAL_DIR, "generated_data")  # synthetic thermal

os.makedirs(THEMIS_DIR, exist_ok=True)

print("Thermal root :", THERMAL_DIR)
print("THEMIS output:", THEMIS_DIR)

C:\Users\Utente\Desktop\lavatube_paper\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Thermal root : data\thermal_data
THEMIS output: data\thermal_data\themis_data

## 1. Load the training dataset

These are the same rows the model trains on, so every image gets a coordinate.

In [2]:
image_data = pd.read_json(DATASET_JSON)

class_names = {
    0: "Vertical Pit/Skylight",
    1: "Shallow Pit Chain",
    2: "Sloped Pit",
    3: "Plain Terrain",
}

print(f"{len(image_data)} images")
print(image_data["category_id"].map(class_names).value_counts().to_string())

2374 images
category_id
Shallow Pit Chain        657
Vertical Pit/Skylight    625
Sloped Pit               564
Plain Terrain            528

## 2. Coordinates

`image_dataset.json` already carries `lat`, `lon_east` and each crop's ground
extent, all computed once when the two source datasets were merged in
`data_overview.ipynb`. Nothing here needs to touch a raster.

Those coordinates come from `themis_coordinates.center_latlon`, which reads each
crop's own georeferencing and repairs a malformed CRS present in the
plain-terrain products: the standard parallel was written into
`latitude_of_origin` with `standard_parallel_1` left at 0, a known planetary-PDS
quirk. Read literally, that offsets latitude by exactly the standard parallel
(up to 45 deg here, ~2600 km) and mis-scales longitude. Section 3 validates the
repair against independently derived values.

If an older `image_dataset.json` without those columns is loaded, the cell falls
back to reading the rasters (slow: a couple of minutes for ~2400 files).

In [3]:
PRECOMPUTED = ["lat", "lon_east", "ground_width_m", "ground_height_m"]
has_coords = set(PRECOMPUTED).issubset(image_data.columns)

if has_coords:
    print("Using precomputed coordinates and extents from image_dataset.json")
    coordinates = image_data[
        ["image_name", "img_path", "category_id", *PRECOMPUTED]
    ].copy()
else:
    print("Columns missing -- recomputing from the rasters "
          "(re-run data_overview.ipynb to avoid this)")
    records = []
    for row in tqdm(
        image_data.itertuples(index=False),
        total=len(image_data),
        desc="Reading georeferencing",
    ):
        path = os.path.join(row.img_path, row.image_name)
        lat, lon = center_latlon(path)
        width_m, height_m = ground_extent_m(path)
        records.append({
            "image_name": row.image_name,
            "img_path": row.img_path,
            "category_id": row.category_id,
            "lat": lat,
            "lon_east": lon,
            "ground_width_m": width_m,
            "ground_height_m": height_m,
        })
    coordinates = pd.DataFrame(records)

coordinates["themis_px_across"] = coordinates["ground_width_m"] / THEMIS_GSD_M
coordinates.head()

Using precomputed coordinates and extents from image_dataset.json

,image_name,img_path,category_id,lat,lon_east,ground_width_m,ground_height_m,themis_px_across
0,ESP_011386_2065_RED_resized_0.5_lbl_0.tiff,data/DeepLandforms_dataset,0,26.148686,259.343078,864.5000,864.0,8.645000
1,ESP_011386_2065_RED_resized_0.5_lbl_1.tiff,data/DeepLandforms_dataset,1,26.124130,259.347565,1058.0000,1058.0,10.580000
2,ESP_011386_2065_RED_resized_1_lbl_0.tiff,data/DeepLandforms_dataset,0,26.148829,259.342953,1212.0000,1212.0,12.120000
3,ESP_011386_2065_RED_resized_1_lbl_1.tiff,data/DeepLandforms_dataset,1,26.124257,259.347462,1540.0000,1540.0,15.400000
4,ESP_011386_2065_RED_resized_2_lbl_0.tiff,data/DeepLandforms_dataset,0,26.148829,259.342960,2016.2625,2016.0,20.162625

## 3. Validate against the label-derived coordinates

The plain-terrain crops ship with `lat_center` / `lon_center` computed
independently from the source PDS label bounds, which gives us ground truth for
that half of the dataset.

Expect ~0 difference for the Equirectangular products. The Polar Stereographic
ones differ by a few tenths of a degree because the CSV interpolates linearly
between label corners, which degrades near the poles -- there the value derived
here is the more accurate of the two.

In [4]:
plain_truth = pd.read_csv(
    os.path.join(DATA_PATH, "plain_terrain_dataset", "plain_terrain_annotations.csv")
)

check = coordinates.merge(
    plain_truth[["image_name", "file_name", "lat_center", "lon_center"]],
    on="image_name",
    how="inner",
)

check["d_lat"] = (check["lat"] - check["lat_center"]).abs()
check["d_lon"] = ((check["lon_east"] - check["lon_center"] % 360 + 180) % 360 - 180).abs()

print(f"Cross-checked {len(check)} plain-terrain crops\n")
print(
    check.groupby("file_name")[["d_lat", "d_lon"]]
    .max()
    .round(4)
    .to_string()
)

Cross-checked 528 plain-terrain crops

                      d_lat   d_lon
file_name
ESP_011287_2165_RED  0.0000  0.0000
ESP_011293_1710_RED  0.0000  0.0000
ESP_011325_1845_RED  0.0000  0.0000
ESP_011335_1005_RED  0.2511  0.3818
ESP_011999_1305_RED  0.0000  0.0000
ESP_012016_1800_RED  0.0000  0.0000
ESP_043599_1650_RED  0.0000  0.0000
ESP_087433_2545_RED  0.0754  0.3644

## 4. How much thermal signal is actually there?

At ~100 m/pixel a HiRISE crop covers only a handful of THEMIS samples. This is
why the thermal stream gets its own small encoder instead of sharing the HiRISE
backbone, and why we extract a fixed window around each site rather than
matching the crop's exact footprint: a fixed `32 x 32` window (~3.2 km) is a
consistent tensor shape and includes surrounding terrain, which is what makes
the pit-versus-background temperature contrast measurable.

In [5]:
spans = coordinates["themis_px_across"]

print("THEMIS pixels across a crop:")
print(f"  min    {spans.min():6.1f}")
print(f"  median {spans.median():6.1f}")
print(f"  max    {spans.max():6.1f}")
print()
print(f"Crops smaller than one THEMIS pixel: {(spans < 1).sum()}")
print(f"Fixed extraction window: 32 x 32 THEMIS px "
      f"= {32 * THEMIS_GSD_M / 1000:.1f} x {32 * THEMIS_GSD_M / 1000:.1f} km")

THEMIS pixels across a crop:
  min       0.4
  median   16.0
  max      80.1

Crops smaller than one THEMIS pixel: 56
Fixed extraction window: 32 x 32 THEMIS px = 3.2 x 3.2 km

## 5. Deduplicate into query sites

Crops closer together than a THEMIS pixel resolve to the same thermal data, and
many crops are multi-resolution replicas of the same landform. Grouping them
onto a coarse grid collapses the number of network queries substantially --
Phase 1 and Phase 2 both hit remote archives, so this matters.

The grid step below is half the extraction window, so any two crops sharing a
site also share almost all of their thermal window.

In [6]:
GRID_DEG = 0.05  # ~3 km at the equator, about half the 32-px window

coordinates["site_lat"] = (coordinates["lat"] / GRID_DEG).round() * GRID_DEG
coordinates["site_lon"] = (coordinates["lon_east"] / GRID_DEG).round() * GRID_DEG

query_sites = (
    coordinates
    .groupby(["site_lat", "site_lon"], as_index=False)
    .agg(
        n_images=("image_name", "size"),
        categories=("category_id", lambda s: sorted(set(s))),
    )
    .sort_values(["site_lat", "site_lon"])
    .reset_index(drop=True)
)

query_sites["site_id"] = [f"site_{i:04d}" for i in range(len(query_sites))]

print(f"{len(coordinates)} images -> {len(query_sites)} unique query sites")
query_sites.head()

2374 images -> 357 unique query sites

   site_lat  site_lon  n_images categories    site_id
0    -79.75    234.95         1        [3]  site_0000
1    -79.75    235.10         1        [3]  site_0001
2    -79.75    235.15         1        [3]  site_0002
3    -79.70    234.95         1        [3]  site_0003
4    -79.70    235.20         1        [3]  site_0004

## 6. Save the retrieval manifest

* `data/thermal_data/image_coordinates.csv` — one row per training image, with
  its site assignment. This is what the dataset loader will use to find the
  right thermal window, and it serves the synthetic pipeline in
  `generated_data/` equally well.
* `data/thermal_data/themis_data/themis_query_sites.csv` — the deduplicated
  sites to actually query.

In [7]:
# map every image to the site that will hold its thermal data
site_lookup = query_sites.set_index(["site_lat", "site_lon"])["site_id"]
coordinates["site_id"] = coordinates.set_index(["site_lat", "site_lon"]).index.map(site_lookup)

coord_path = os.path.join(THERMAL_DIR, "image_coordinates.csv")
sites_path = os.path.join(THEMIS_DIR, "themis_query_sites.csv")

coordinates.to_csv(coord_path, index=False)
query_sites.to_csv(sites_path, index=False)

print("Saved:")
print(" ", coord_path, f"({len(coordinates)} rows)")
print(" ", sites_path, f"({len(query_sites)} rows)")

Saved:
  data\thermal_data\image_coordinates.csv (2374 rows)
  data\thermal_data\themis_data\themis_query_sites.csv (357 rows)

## 7. Phase 1 — find THEMIS observations per site

`themis_measurements.py` queries the ODE ArcGIS IRPBT4 footprint layer for one
point and returns the observations covering it, with acquisition time and Mars
local solar time. Local solar time is the useful axis here: the diagnostic
signal for a cave-connected pit is that it stays anomalously warm at night, so a
sequence spanning different times of day is what the temporal model needs.

**These are live network calls to an external archive.** The loop is disabled by
default -- set `RUN_PHASE_1 = True` to actually fetch, and consider starting with
`query_sites.head(...)` rather than the full set.

In [8]:
from themis_measurements import query_point, build_records

RUN_PHASE_1 = True          # set True to hit the network
SITES_TO_QUERY = query_sites  # e.g. query_sites.head(5) for a trial run

observations_path = os.path.join(THEMIS_DIR, "themis_observations.csv")

if RUN_PHASE_1:
    found = []

    for site in tqdm(
        SITES_TO_QUERY.itertuples(index=False),
        total=len(SITES_TO_QUERY),
        desc="Phase 1: footprint queries",
    ):
        try:
            payload = query_point(site.site_lat, site.site_lon)
            for record in build_records(payload, site.site_lon):
                record["site_id"] = site.site_id
                record["site_lat"] = site.site_lat
                record["site_lon"] = site.site_lon
                found.append(record)
        except Exception as exc:
            print(f"  {site.site_id} failed: {exc}")

    observations = pd.DataFrame(found)
    observations.to_csv(observations_path, index=False)
    print(f"\n{len(observations)} observations across "
          f"{observations['site_id'].nunique()} sites -> {observations_path}")
else:
    print("Phase 1 skipped (RUN_PHASE_1 is False).")
    if os.path.exists(observations_path):
        observations = pd.read_csv(observations_path)
        print(f"Loaded {len(observations)} previously saved observations.")
    else:
        observations = pd.DataFrame()
        print("No saved observations yet.")

Phase 1: footprint queries: 100%|██████████| 357/357 [04:53<00:00,  1.22it/s]

3339 observations across 356 sites -> data\thermal_data\themis_data\themis_observations.csv

### What local solar times are actually available?

The diagnostic signal for a cave-connected pit is that it stays anomalously warm
at night, so what the temporal branch needs is *contrast across time of day*.

Do not assume a tidy midday / morning / midnight triple is obtainable. Mars
Odyssey flies a near sun-synchronous orbit, so a given site is revisited near
only a couple of local solar times -- broadly a day pass and a night pass about
12 h apart -- with that local time drifting slowly over the mission rather than
sweeping the whole diurnal cycle. Check the real distribution before choosing a
sequence policy.

In [9]:
if len(observations):
    lmst = observations["mars_lmst_decimal_hours"].dropna()

    counts, _ = np.histogram(lmst, bins=24, range=(0, 24))
    print("Observations by Mars local solar time (all sites):")
    for hour, count in enumerate(counts):
        if count:
            print(f"  {hour:02d}:00  {'#' * min(count, 60)} {count}")

    per_site_span = (
        observations.groupby("site_id")["mars_lmst_decimal_hours"]
        .agg(lambda s: s.max() - s.min())
    )
    print(f"\nLocal-time span within a site: median {per_site_span.median():.1f} h, "
          f"max {per_site_span.max():.1f} h")
else:
    print("Run Phase 1 first.")

Observations by Mars local solar time (all sites):
  03:00  ######################## 24
  04:00  ############################################################ 67
  05:00  ############################################################ 158
  06:00  ############################################################ 1221
  07:00  ############################################################ 221
  08:00  ############################################################ 78
  10:00  ############## 14
  15:00  ############################################################ 67
  16:00  ############################################################ 85
  17:00  ############################### 31
  18:00  ############################################################ 1221
  19:00  ############################################################ 151
  20:00  # 1

Local-time span within a site: median 12.3 h, max 14.9 h

### Choosing a sequence per site

Rather than targeting fixed clock hours that may not exist, this picks the `T`
observations that are maximally separated on the 24 h circle (greedy
farthest-point selection). That extracts whatever diurnal contrast a site
genuinely offers -- a day/night pair when that is all there is, a wider spread
when more exists -- and degrades gracefully instead of silently returning three
near-identical frames.

Frames are then ordered by local solar time so the TCN sees a coherent
progression rather than an arbitrary permutation.

In [10]:
SEQUENCE_LENGTH = 3  # must match Hirise_Dataset(sequence_length=...)


def circular_gap(a, b, period=24.0):
    """Shortest distance between two local-solar-time values, in hours."""
    diff = abs(a - b) % period
    return min(diff, period - diff)


def spread_over_local_time(group, n):
    """Pick n rows whose local solar times are as far apart as possible."""
    usable = group.dropna(subset=["mars_lmst_decimal_hours"])
    if len(usable) <= n:
        return usable.sort_values("mars_lmst_decimal_hours")

    hours = usable["mars_lmst_decimal_hours"].tolist()

    # Seed with the earliest pass, then repeatedly add the observation
    # furthest (in time-of-day) from everything already selected.
    picked = [int(np.argmin(hours))]
    while len(picked) < n:
        best = max(
            (i for i in range(len(hours)) if i not in picked),
            key=lambda i: min(circular_gap(hours[i], hours[j]) for j in picked),
        )
        picked.append(best)

    return usable.iloc[sorted(picked, key=lambda i: hours[i])]


if len(observations):
    chosen = (
        observations
        .groupby("site_id", group_keys=False)
        .apply(spread_over_local_time, n=SEQUENCE_LENGTH)
    )

    counts = chosen.groupby("site_id").size()
    print(f"Sites with a full sequence of {SEQUENCE_LENGTH}: "
          f"{(counts == SEQUENCE_LENGTH).sum()} / {len(counts)}")
    print(f"Sites with fewer (not enough passes): {(counts < SEQUENCE_LENGTH).sum()}")

    gaps = chosen.groupby("site_id")["mars_lmst_decimal_hours"].agg(
        lambda s: max(s) - min(s)
    )
    print(f"\nSelected local-time spread: median {gaps.median():.1f} h, "
          f"min {gaps.min():.1f} h, max {gaps.max():.1f} h")

    # Sites whose passes all land at one local time carry no diurnal contrast:
    # their frames are near-duplicates and the temporal branch has nothing to
    # learn from them. Worth excluding or flagging before training.
    flat = gaps[gaps < 0.5]
    print(f"Sites with effectively no diurnal contrast (<0.5 h spread): {len(flat)}")
    if len(flat):
        print(f"  e.g. {', '.join(flat.index[:5])}")

    display(chosen.head(10))
else:
    chosen = pd.DataFrame()
    print("Run Phase 1 first.")

Sites with a full sequence of 3: 336 / 356
Sites with fewer (not enough passes): 20

Selected local-time spread: median 12.0 h, min 0.0 h, max 14.8 h
Sites with effectively no diurnal contrast (<0.5 h spread): 26
  e.g. site_0047, site_0048, site_0071, site_0072, site_0075

C:\Users\Utente\AppData\Local\Temp\ipykernel_153952\536390225.py:35: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(spread_over_local_time, n=SEQUENCE_LENGTH)

,observation_id,product_id_raw,utc_start,utc_end,mars_lmst_decimal_hours,mars_lmst_hhmm,solar_longitude_deg,emission_angle_deg,incidence_angle_deg,phase_angle_deg,product_version,product_lid,ode_id,site_id,site_lat,site_lon
8,I90212002,i90212002pbt,2022-04-16T08:15:57.830Z,2022-04-16T08:18:57.568Z,7.3011,07:18,209.778,1.587,71.050,71.498,2.1,urn:nasa:pds:ody.themis.geo:data_irpbt:i902120...,55099005,site_0000,-79.75,234.95
19,I93121009,i93121009pbt,2022-12-11T20:51:41.273Z,2022-12-11T20:57:40.210Z,10.0888,10:05,352.644,1.727,84.634,84.562,2.0,urn:nasa:pds:ody.themis.geo:data_irpbt:i931210...,48882258,site_0000,-79.75,234.95
10,I91228004,i91228004pbt,2022-07-08T23:55:31.880Z,2022-07-08T23:57:31.880Z,17.2442,17:15,262.260,1.354,63.937,64.315,2.1,urn:nasa:pds:ody.themis.geo:data_irpbt:i912280...,53569732,site_0000,-79.75,234.95
32,I90212002,i90212002pbt,2022-04-16T08:15:57.830Z,2022-04-16T08:18:57.568Z,7.3111,07:19,209.778,1.587,71.050,71.498,2.1,urn:nasa:pds:ody.themis.geo:data_irpbt:i902120...,55099005,site_0001,-79.75,235.10
43,I93121009,i93121009pbt,2022-12-11T20:51:41.273Z,2022-12-11T20:57:40.210Z,10.0988,10:06,352.644,1.727,84.634,84.562,2.0,urn:nasa:pds:ody.themis.geo:data_irpbt:i931210...,48882258,site_0001,-79.75,235.10
34,I91228004,i91228004pbt,2022-07-08T23:55:31.880Z,2022-07-08T23:57:31.880Z,17.2542,17:15,262.260,1.354,63.937,64.315,2.1,urn:nasa:pds:ody.themis.geo:data_irpbt:i912280...,53569732,site_0001,-79.75,235.10
56,I90212002,i90212002pbt,2022-04-16T08:15:57.830Z,2022-04-16T08:18:57.568Z,7.3144,07:19,209.778,1.587,71.050,71.498,2.1,urn:nasa:pds:ody.themis.geo:data_irpbt:i902120...,55099005,site_0002,-79.75,235.15
67,I93121009,i93121009pbt,2022-12-11T20:51:41.273Z,2022-12-11T20:57:40.210Z,10.1021,10:06,352.644,1.727,84.634,84.562,2.0,urn:nasa:pds:ody.themis.geo:data_irpbt:i931210...,48882258,site_0002,-79.75,235.15
58,I91228004,i91228004pbt,2022-07-08T23:55:31.880Z,2022-07-08T23:57:31.880Z,17.2576,17:15,262.260,1.354,63.937,64.315,2.1,urn:nasa:pds:ody.themis.geo:data_irpbt:i912280...,53569732,site_0002,-79.75,235.15
77,I89900002,i89900002pbt,2022-03-21T15:42:05.032Z,2022-03-21T15:45:04.770Z,7.2331,07:14,194.423,1.606,76.761,77.282,2.1,urn:nasa:pds:ody.themis.geo:data_irpbt:i899000...,55094825,site_0003,-79.70,234.95

## 8. Phase 2 — extract the thermal windows

`themis_id_to_thermal_value.py` downloads a whole PBT product and decodes it to
a `.npy`. That is far more than this pipeline needs: products run 0.4-126 MB
(median 22 MB) and the model uses a 32x32 patch, about 4 KB. The 312 products
behind a T=3 sequence cost roughly 7 GB of cache plus 7 GB of decoded arrays.

The ASU archive supports HTTP range requests, so GDAL can open a product through
`/vsicurl/` and fetch only the bytes covering the window we want.
`themis_windows.read_window_for_observation` does that -- about 2 s per window,
a few megabytes in total instead of ~14 GB, and nothing cached locally.

Values are **brightness temperature in Kelvin**, with **0 meaning no data**
(not "very cold"). Mask it before computing any statistic.

This is also the step that produces the final arrays, so the separate
window-cutting stage the earlier draft deferred is no longer needed.

In [ ]:
from themis_windows import read_window_for_observation, NODATA_KELVIN
from themis_id_to_thermal_value import ensure_index

RUN_PHASE_2 = True  # set True to fetch windows over the network
WINDOW_PX = 32

windows_dir = os.path.join(THEMIS_DIR, "windows")
os.makedirs(windows_dir, exist_ok=True)

if RUN_PHASE_2 and len(chosen):
    index_path = ensure_index()  # ~42 MB, cached after the first call
    manifest = []

    for site_id, group in tqdm(
        chosen.groupby("site_id"), desc="Phase 2: windows", total=chosen.site_id.nunique()
    ):
        frames, used = [], []

        for obs in group.itertuples():
            try:
                patch = read_window_for_observation(
                    obs.observation_id, obs.site_lat, obs.site_lon,
                    size=WINDOW_PX, index_path=index_path,
                )
            except Exception as exc:
                print(f"  {site_id}/{obs.observation_id}: {type(exc).__name__} {exc}")
                patch = None

            if patch is None:
                continue

            frames.append(patch)
            used.append({
                "observation_id": obs.observation_id,
                "mars_lmst_decimal_hours": obs.mars_lmst_decimal_hours,
                "valid_fraction": float((patch != NODATA_KELVIN).mean()),
                "kelvin_median": float(np.median(patch[patch != NODATA_KELVIN]))
                                 if (patch != NODATA_KELVIN).any() else None,
            })

        if not frames:
            continue

        # (T, 1, WINDOW_PX, WINDOW_PX) -- the shape the model's thermal branch takes
        stack = np.stack(frames)[:, None, :, :].astype(np.float32)
        np.save(os.path.join(windows_dir, f"{site_id}.npy"), stack)
        manifest.append({"site_id": site_id, "n_frames": len(frames), "frames": used})

    with open(os.path.join(THEMIS_DIR, "window_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"\n{len(manifest)} sites written to {windows_dir}")
else:
    print("Phase 2 skipped (RUN_PHASE_2 is False, or no observations selected).")

Using cached ASU index: themis_phase2_cache\CMIDX_ODTIP.TAB

Phase 2: windows:   5%|▍         | 17/356 [00:22<05:55,  1.05s/it]

  site_0017/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   5%|▌         | 18/356 [00:28<14:21,  2.55s/it]

  site_0018/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   5%|▌         | 19/356 [00:30<12:54,  2.30s/it]

  site_0019/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   6%|▌         | 20/356 [00:30<09:55,  1.77s/it]

  site_0020/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   6%|▌         | 21/356 [00:31<07:45,  1.39s/it]

  site_0021/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   6%|▌         | 22/356 [00:31<06:18,  1.13s/it]

  site_0022/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   6%|▋         | 23/356 [00:33<07:11,  1.30s/it]

  site_0023/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   7%|▋         | 24/356 [00:33<05:54,  1.07s/it]

  site_0024/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   7%|▋         | 25/356 [00:34<05:01,  1.10it/s]

  site_0025/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   7%|▋         | 26/356 [00:34<04:21,  1.26it/s]

  site_0026/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   8%|▊         | 27/356 [00:37<06:47,  1.24s/it]

  site_0027/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   8%|▊         | 28/356 [00:37<05:36,  1.03s/it]

  site_0028/IA1672010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:   9%|▉         | 33/356 [00:53<15:29,  2.88s/it]

  site_0033/IA0369010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  10%|▉         | 34/356 [00:57<15:59,  2.98s/it]

  site_0034/IA0369010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  10%|▉         | 35/356 [00:59<14:04,  2.63s/it]

  site_0035/IA0369010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  10%|█         | 36/356 [01:01<13:48,  2.59s/it]

  site_0036/IA0369010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  10%|█         | 37/356 [01:03<12:16,  2.31s/it]

  site_0037/IA0369010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  11%|█         | 38/356 [01:05<11:39,  2.20s/it]

  site_0038/IA0369010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  11%|█         | 39/356 [01:07<11:23,  2.16s/it]

  site_0039/IA2497002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  11%|█         | 40/356 [01:11<15:04,  2.86s/it]

  site_0040/IA2472002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  12%|█▏        | 41/356 [01:17<18:56,  3.61s/it]

  site_0041/IA2497002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  12%|█▏        | 42/356 [01:22<21:57,  4.20s/it]

  site_0042/IA2690003PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  12%|█▏        | 43/356 [01:28<24:10,  4.63s/it]

  site_0043/IA1685002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  13%|█▎        | 45/356 [01:38<24:50,  4.79s/it]

  site_0045/IA1823002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  13%|█▎        | 46/356 [01:42<24:53,  4.82s/it]

  site_0046/IA1018019PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  13%|█▎        | 47/356 [01:47<24:19,  4.72s/it]

  site_0047/IA4431002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  13%|█▎        | 48/356 [01:49<20:42,  4.03s/it]

  site_0048/IA4431002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  14%|█▍        | 49/356 [01:50<15:44,  3.08s/it]

  site_0049/IA1991007PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0049/IA4431002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  15%|█▍        | 52/356 [01:57<13:32,  2.67s/it]

  site_0052/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  15%|█▍        | 53/356 [02:02<16:42,  3.31s/it]

  site_0053/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  15%|█▌        | 54/356 [02:05<15:43,  3.12s/it]

  site_0054/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  15%|█▌        | 55/356 [02:08<15:13,  3.04s/it]

  site_0055/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  16%|█▌        | 56/356 [02:11<15:09,  3.03s/it]

  site_0056/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  16%|█▌        | 57/356 [02:11<11:32,  2.32s/it]

  site_0057/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  16%|█▋        | 58/356 [02:13<10:51,  2.19s/it]

  site_0058/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  17%|█▋        | 59/356 [02:14<08:31,  1.72s/it]

  site_0059/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  17%|█▋        | 60/356 [02:17<10:24,  2.11s/it]

  site_0060/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  17%|█▋        | 61/356 [02:20<11:44,  2.39s/it]

  site_0061/IA1829010PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  17%|█▋        | 62/356 [02:26<17:35,  3.59s/it]

  site_0062/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  18%|█▊        | 63/356 [02:29<16:44,  3.43s/it]

  site_0063/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  18%|█▊        | 64/356 [02:31<14:12,  2.92s/it]

  site_0064/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  18%|█▊        | 65/356 [02:33<12:42,  2.62s/it]

  site_0065/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  19%|█▊        | 66/356 [02:34<10:05,  2.09s/it]

  site_0066/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  19%|█▉        | 67/356 [02:36<09:32,  1.98s/it]

  site_0067/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  19%|█▉        | 68/356 [02:38<10:36,  2.21s/it]

  site_0068/IA4404002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  19%|█▉        | 69/356 [02:40<09:04,  1.90s/it]

  site_0069/IA2079006PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  20%|█▉        | 70/356 [02:44<12:43,  2.67s/it]

  site_0070/IA2752004PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  20%|█▉        | 71/356 [02:47<12:54,  2.72s/it]

  site_0070/IA1935002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0071/IA2522001PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0071/IA1923003PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  20%|██        | 72/356 [02:49<12:38,  2.67s/it]

  site_0072/IA1923003PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  21%|██        | 75/356 [03:02<17:12,  3.67s/it]

  site_0075/IA2522001PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0075/IA1923003PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  21%|██▏       | 76/356 [03:03<13:48,  2.96s/it]

  site_0076/IA1636002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0076/IA1923003PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  22%|██▏       | 80/356 [03:15<15:26,  3.36s/it]

  site_0080/IA2547002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  23%|██▎       | 81/356 [03:19<16:09,  3.52s/it]

  site_0081/IA5947002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  23%|██▎       | 82/356 [03:22<15:28,  3.39s/it]

  site_0081/IA1898002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0082/IA2547002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  23%|██▎       | 83/356 [03:25<15:31,  3.41s/it]

  site_0083/IA4724005PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  24%|██▎       | 84/356 [03:28<14:55,  3.29s/it]

  site_0083/IA2472002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0084/IA2141002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  24%|██▍       | 85/356 [03:34<17:26,  3.86s/it]

  site_0085/IA2547002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  24%|██▍       | 86/356 [03:37<17:02,  3.79s/it]

  site_0086/IA2141002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  24%|██▍       | 87/356 [03:41<17:20,  3.87s/it]

  site_0087/IA2141002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  25%|██▍       | 88/356 [03:42<12:32,  2.81s/it]

  site_0087/IA2497002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0088/IA2547002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  25%|██▌       | 89/356 [03:44<11:21,  2.55s/it]

  site_0089/IA2141002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  25%|██▌       | 90/356 [03:45<10:30,  2.37s/it]

  site_0090/IA2141002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  26%|██▌       | 91/356 [03:46<07:46,  1.76s/it]

  site_0090/IA2497002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0091/IA2116015PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  26%|██▌       | 92/356 [03:48<07:55,  1.80s/it]

  site_0091/IA1898002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0092/IA2665003PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0092/IA4724005PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0093/IA5947002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  26%|██▋       | 94/356 [03:49<05:24,  1.24s/it]

  site_0093/IA1611002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0094/IA5947002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  27%|██▋       | 95/356 [03:50<05:22,  1.24s/it]

  site_0094/IA1611002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0095/IA4724005PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  27%|██▋       | 96/356 [03:53<07:14,  1.67s/it]

  site_0095/IA2472002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  27%|██▋       | 97/356 [03:58<11:26,  2.65s/it]

  site_0096/IA1274002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0097/IA2690003PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  28%|██▊       | 98/356 [03:59<09:35,  2.23s/it]

  site_0097/IA1299002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0098/IA4724005PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  28%|██▊       | 99/356 [04:00<07:13,  1.69s/it]

  site_0098/IA2472002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0099/IA4724005PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  28%|██▊       | 100/356 [04:03<08:44,  2.05s/it]

  site_0099/IA2472002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  28%|██▊       | 101/356 [04:05<09:15,  2.18s/it]

  site_0100/IA2472002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  29%|██▊       | 102/356 [04:08<09:41,  2.29s/it]

  site_0101/IA2472002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0102/IA5947002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  29%|██▉       | 103/356 [04:10<09:23,  2.23s/it]

  site_0102/IA0438002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0103/IA4150002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  29%|██▉       | 104/356 [04:12<09:45,  2.32s/it]

  site_0103/IA1898002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  29%|██▉       | 105/356 [04:15<09:29,  2.27s/it]

  site_0104/IA1274002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0105/IA5348002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  30%|██▉       | 106/356 [04:16<07:51,  1.89s/it]

  site_0105/IA1324001PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0106/IA5635002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  30%|███       | 107/356 [04:17<07:07,  1.72s/it]

  site_0106/IA1611002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0107/IA5947002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  30%|███       | 108/356 [04:18<06:14,  1.51s/it]

  site_0107/IA0438002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0108/IA5348002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  31%|███       | 109/356 [04:18<04:49,  1.17s/it]

  site_0108/IA1324001PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0109/IA5348002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  31%|███       | 110/356 [04:19<03:52,  1.06it/s]

  site_0109/IA1324001PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0110/IA5635002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  31%|███       | 111/356 [04:20<04:09,  1.02s/it]

  site_0110/IA1611002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0111/IA5685002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0111/IA0775001PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  31%|███▏      | 112/356 [04:23<06:30,  1.60s/it]

  site_0112/IA5635002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  32%|███▏      | 113/356 [04:24<05:48,  1.43s/it]

  site_0112/IA1611002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  32%|███▏      | 115/356 [04:33<10:54,  2.72s/it]

  site_0115/IA4100002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  33%|███▎      | 116/356 [04:35<10:22,  2.59s/it]

  site_0115/IA2733023PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  33%|███▎      | 117/356 [04:38<10:33,  2.65s/it]

  site_0116/IA2794023PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  33%|███▎      | 118/356 [04:40<09:17,  2.34s/it]

  site_0118/IA4100002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  33%|███▎      | 119/356 [04:41<07:32,  1.91s/it]

  site_0118/IA2733023PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  34%|███▎      | 120/356 [04:42<07:22,  1.88s/it]

  site_0119/IA2794023PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  35%|███▍      | 123/356 [04:51<09:03,  2.33s/it]

  site_0122/IA2794023PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  37%|███▋      | 133/356 [05:18<13:28,  3.63s/it]

  site_0132/IA2634002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  40%|███▉      | 142/356 [05:45<09:52,  2.77s/it]

  site_0142/IA3576002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  40%|████      | 143/356 [05:46<08:04,  2.28s/it]

  site_0142/IA1324001PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  41%|████      | 146/356 [05:56<10:24,  2.97s/it]

  site_0145/IA0700002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  41%|████▏     | 147/356 [05:58<09:40,  2.78s/it]

  site_0146/IA0700002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0147/IA5635002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  42%|████▏     | 148/356 [06:00<08:40,  2.50s/it]

  site_0147/IA1037002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  42%|████▏     | 149/356 [06:03<09:19,  2.71s/it]

  site_0149/IA4699005PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  42%|████▏     | 151/356 [06:11<11:29,  3.36s/it]

  site_0150/IA2783023PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  43%|████▎     | 152/356 [06:14<10:09,  2.99s/it]

  site_0151/IA2783023PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0152/IA4774002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  43%|████▎     | 153/356 [06:16<09:17,  2.75s/it]

  site_0152/IA2833023PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  43%|████▎     | 154/356 [06:20<11:10,  3.32s/it]

  site_0153/IA2808023PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  44%|████▎     | 155/356 [06:25<11:56,  3.57s/it]

  site_0155/IA4674002PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  44%|████▍     | 156/356 [06:29<13:13,  3.97s/it]

  site_0156/IA4724005PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  44%|████▍     | 157/356 [06:32<11:16,  3.40s/it]

  site_0157/IA4699005PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  44%|████▍     | 158/356 [06:39<14:51,  4.50s/it]

  site_0158/IA4674002PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0158/IA2733023PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  45%|████▍     | 159/356 [06:41<12:45,  3.88s/it]

  site_0159/IA6246022PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  45%|████▌     | 161/356 [06:43<08:29,  2.61s/it]

  site_0160/IA2808023PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0161/IA6059005PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  46%|████▌     | 162/356 [06:46<08:47,  2.72s/it]

  site_0161/IA2059019PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0162/IA6059005PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  46%|████▌     | 163/356 [06:47<07:14,  2.25s/it]

  site_0162/IA2059019PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  47%|████▋     | 168/356 [07:08<10:54,  3.48s/it]

  site_0168/IA1797025PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  48%|████▊     | 170/356 [07:19<14:09,  4.56s/it]

  site_0169/IA2908015PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0170/IA2159031PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  48%|████▊     | 172/356 [07:23<10:09,  3.31s/it]

  site_0171/IA2908015PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  49%|████▊     | 173/356 [07:26<09:10,  3.01s/it]

  site_0172/IA2908015PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0173/IA2159031PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  49%|████▉     | 174/356 [07:28<08:16,  2.73s/it]

  site_0174/IA2159031PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  49%|████▉     | 175/356 [07:32<09:12,  3.05s/it]

  site_0175/IA2159031PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  49%|████▉     | 176/356 [07:32<06:54,  2.30s/it]

  site_0176/IA1785019PBT: ValueError Use a THEMIS observation ID such as I88015002
  site_0176/IA2672001PBT: ValueError Use a THEMIS observation ID such as I88015002

Phase 2: windows:  51%|█████     | 180/356 [07:53<12:47,  4.36s/it]

  site_0179/IA2808023PBT: ValueError Use a THEMIS observation ID such as I88015002

## 9. Inspect what was extracted

Sanity-check the windows before training on them. What to look for:

* **Valid fraction** -- sites near a product edge lose pixels to no-data. A site
  whose windows are mostly zeros carries little signal.
* **Diurnal contrast** -- night frames should be markedly colder than day
  frames. Observed on real products: ~157-167 K at night against ~254-277 K in
  the afternoon. A site whose frames all sit at one temperature has no contrast
  for the temporal branch to use, whatever its local-time spread suggested.

In [ ]:
manifest_path = os.path.join(THEMIS_DIR, "window_manifest.json")

if os.path.exists(manifest_path):
    with open(manifest_path) as f:
        manifest = json.load(f)

    frames = pd.DataFrame([
        {"site_id": entry["site_id"], **frame}
        for entry in manifest for frame in entry["frames"]
    ])

    print(f"{len(manifest)} sites, {len(frames)} frames")
    print(f"median valid fraction: {frames.valid_fraction.median():.2f}")
    print(f"sites with any frame <50% valid: "
          f"{frames[frames.valid_fraction < 0.5].site_id.nunique()}")

    span = frames.groupby("site_id")["kelvin_median"].agg(lambda s: s.max() - s.min())
    print(f"\nper-site temperature span (K): median {span.median():.1f}, "
          f"min {span.min():.1f}, max {span.max():.1f}")
    print(f"sites with <10 K span (little diurnal contrast): {(span < 10).sum()}")

    fig, axs = plt.subplots(1, 2, figsize=(14, 4))
    frames.kelvin_median.hist(bins=40, ax=axs[0])
    axs[0].set_title("Window median temperature")
    axs[0].set_xlabel("Kelvin")
    span.hist(bins=40, ax=axs[1])
    axs[1].set_title("Per-site day/night span")
    axs[1].set_xlabel("Kelvin")
    for ax in axs:
        ax.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()
else:
    print("No windows yet -- run Phase 2 with RUN_PHASE_2 = True.")

## 10. Wiring the windows into training

`Hirise_Dataset` currently fabricates its thermal sequence
(`generate_synthetic_thermal=True`, a `torch.randn` placeholder shaped
`(T, 1, 32, 32)`). To train on the real data, load
`data/thermal_data/themis_data/windows/{site_id}.npy` instead, looking up each
image's `site_id` through `image_coordinates.csv`.

Two things to handle when doing that:

* **Sites with fewer than `T` frames.** Not every site yields a full sequence;
  the dataset returns a fixed `T`, so short sequences need padding, repetition,
  or exclusion. Padding with no-data zeros is the honest option, but keep it
  consistent with how the masked values are normalised.
* **Normalisation.** Mask `0` before any statistic. Prefer contrast within the
  window (pit against its surroundings) over absolute Kelvin: it is the
  physically invariant quantity, and it is robust to season, latitude, and the
  local-time drift across the mission.

The modality ablation in `model/training.ipynb` is the check that this actually
helped -- with the synthetic placeholder, "thermal" scores at chance and "both"
matches "optical". Real windows should move both.